Many improvements and minor bug-fixes.
Additions with file XCMBuild.xcodeproj/xcshareddata/xcschemes/Test.xcscheme:
 + Added Test Scheme

Additions with file XCMBuild/XCMBuildSystem.h:
 + Added Boiler-Plate code for `XCMBuild.framework` (header)

Additions with file XCMBuild/XCMBuildSystem.m:
 + Added boilerplate code for `XCMBuild.framework` (implementation)

Additions with file XCMBuild/XCMTest/XCMTest.h:
 + Added boilerplate code for `XCMTest` (header)

Additions with file XCMBuild/XCMTest/XCMTest.m:
 + Added Prototype and boilerplate code for `XCMTest` (prototype v2.5)

Additions with file bin/xcode_run_tests.bash:
 + Added shellscript Prototype and Proof-of-concept script for `XCMTest` (PoC v1.0)

Additions with file bin/xcode_run_tool.bash:
 + Added shellscript stub and Proof-of-concept script for `XCMBuild` (PoC v1.0)

Additions with file stubs/ACLs/apfs_dir_CONFIG_ACLs:
 + Added APFS ACL profile stub and Proof-of-concept for `XCMBuild` automation (PoC Config ACLs)

Additions with file stubs/ACLs/apfs_dir_DEVELOPER_ACLs:
 + Added APFS ACL profile stub and Proof-of-concept for `XCMBuild` automation (PoC Dev ACLs)

Additions with file stubs/ACLs/apfs_file_CONFIG_ACLs:
 + Added APFS ACL profile stub and Proof-of-concept for `XCMBuild` automation (PoC Debug ACLs)

Additions with file stubs/Clang/module.modulemap:
 + Added Prototype and boilerplate code for `XCMBuild.framework` (prototype modulemap)

Additions with file stubs/Clang/module.private.modulemap:
 + Added Prototype and boilerplate code for `XCMBuild.framework` (prototype modulemap)

Additions with file stubs/Clang/orderfile:
 + added prototype build order file. (prototype v2.5)

Additions with file stubs/Config/*.xcconfig:
 + Added several Prototype and boilerplate configurations for `XCMBuild.framework` (prototype configurations)

Changes in file .github/tool_shlock_helper.sh:
 - imported and merged common utility script for missing `shlock` support.

Changes in file Makefile:
 cleanup:
	+ cleaned up the clean-up.
 uninstall:
	+ changed uninstall to placeholder as it is not yet implemented.

Changes in file XCMBuild.xcodeproj/project.pbxproj:
 + added Xcode project file and some fixes.

Changes in file XCMBuild.xcodeproj/xcshareddata/xcschemes/*.xcscheme:
 + added Xcode project scheme files.

Changes in file XCMBuild/XCMBuild.h:
 + added umbrella header for `XCMBuild.framework`

Changes in file XCMBuild/XCMShell.h:
 + Added boilerplate code for `XCMBuild.framework` (header)

Changes in file XCMBuild/XCMShell.m:
 + Added boilerplate code for `XCMBuild.framework` (implementation)

Changes in file bin/flatten:
 + Added shellscript stub and Proof-of-concept script for `XCMBuild` (flatten tool)

Changes in file bin/prunefile:
 + Added shellscript stub and Proof-of-concept script for `XCMBuild` (prune tool)

Changes in file bin/serialized:
 + Added shellscript stub and Proof-of-concept script for `XCMBuild` (serialized tool)

Changes in file bin/tool_shlock_helper.bash:
 + Added shellscript stub and Proof-of-concept script for `XCMBuild` (shlock like tool)

Changes in file stubs/*:
 + Added Various stubs and Proof-of-concepts for `XCMBuild.framework` (Misc.)

Changes in file tests/test_bash_shlock_tool.bash:
 + minor fixes and style improvements.

Changes in file tests/test_cc_lines.bash:
 + minor fixes and style improvements.

Changes in file tests/test_codecov_config.bash:
 + minor fixes and style improvements.

Changes in file tests/test_git_config.bash:
 + minor fixes and style improvements.

Changes in file tests/test_plists.bash:
 + minor fixes and style improvements.

Changes in file tests/test_shell_scripts.bash:
 + minor fixes and style improvements.

Changes in file tests/test_spelling.bash:
 + minor style improvements.

diff --git a/bin/serialized b/bin/serialized
--- a/bin/serialized
+++ b/bin/serialized
@@ -1,4 +1,21 @@
 #! /bin/bash
+
+# reactive-firewall/XCMBuild Tool
+# ..................................
+# Copyright (c) 2023, Mr. Walls
+# ..................................
+# Licensed under APACHE-2 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+# ..........................................
+# http://www.apache.org/licenses/LICENSE-2.0
+# ..........................................
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
 # Disclaimer of Warranties.
 # A. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE EXTENT PERMITTED BY
 #    APPLICABLE LAW, USE OF THIS SHELL SCRIPT AND ANY SERVICES PERFORMED
@@ -60,18 +77,25 @@
 #    even if the above stated remedy fails of its essential purpose.
 ################################################################################
 
-# checks if the codcov.yml file is valid
-# exit fast if command is missing
-EXIT_CODE=0 ;
-test -f "${1:-.codecov.yml}" || exit $EXIT_CODE ;
-if [[ ( $(curl --tlsv1.2 --header "Dnt: 1" -fsS --data-binary "@${1:-.codecov.yml}" https://codecov.io/validate 2>/dev/null | grep -Fc "Valid" ) -gt 0) ]] ; then
-	EXIT_CODE=0 ;
-else
-	EXIT_CODE=1 ;
-fi
-#if [[ ( $EXIT_CODE -gt 0 ) ]] ; then
-#	echo "FAIL: codecov.yml validation FAILED." ;
-#else
-#	echo "Ok: codecov.yml validation passed." ;
-#fi
-exit ${EXIT_CODE:255} ;
+
+function safetyCheckSerialized() {
+	if [[ -z ${SCRIPT_INPUT_FILE_COUNT} ]] || [[ -z ${SCRIPT_OUTPUT_FILE_COUNT} ]] ; then
+		echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized script mode. ( unsupported integration )" 1>&2 ;
+		echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: warning: expected serialized script mode. ( unsupported integration ) Hint: Try 'SCRIPT_INPUT_FILE_COUNT=1 ; SCRIPT_OUTPUT_FILE_COUNT=1 ; SCRIPT_INPUT_FILE_0=\${1} ; SCRIPT_OUTPUT_FILE_0=\${2} ; $0 ;' instead?" 1>&2 ;
+		false ;
+	else
+		if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
+			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized input. ( unsupported input )" 1>&2 ;
+			false ;
+		fi ;
+		if [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -lt 0 ) ]] ; then
+			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized output. ( unsupported output )" 1>&2 ;
+			false ;
+		fi ;
+		true ;
+	fi ;
+}
+
+export -f safetyCheckSerialized ;
+
+# source to include
