Highlights in this update:  + Improved stability and performance of the Makefile slightly  + Added some initial comments to the documentation  + some under-the-hood cleanup of the project configurations  + minor bug-fixes for overall build system  + Added a custom icon logo  + added prototype tool scripts
Additions with file bin/dylink2text:
 As part of added prototype tool scripts

Additions with file bin/hmap2text:
 As part of added prototype tool scripts

Additions with file stubs/Icon.icns:
 + Added a custom icon logo

Improved stability and performance in file Makefile:
 headers
 cleanup:
 uninstall:

Changes in file XCMBuild.docc/Acknowledgements.md:
 Added template draft

Changes in file XCMBuild.docc/XCMBuild.md:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild.docc/XCMTest.md:
 As part of minor bug-fixes for overall build system
 Should crash less...

Changes in file XCMBuild.docc/xcrunshell.md:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild.xcodeproj:
 some under-the-hood cleanup of the project configurations

Changes in file XCMBuild/XCMBuild.h:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild/XCMBuildSystem.h:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild/XCMBuildSystem.m:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild/XCMShell.h:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild/XCMShell.m:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild/XCMTest/XCMTest.h:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild/XCMTest/XCMTest.m:
 As part of minor bug-fixes for overall build system

Changes in file XCMBuild/xcrunshell/xcrunshell.h:
 As part of minor bug-fixes for overall build system

Changes in file bin/serialized:
 As part of added prototype tool scripts

Changes in file stubs/Clang/module.private.modulemap:
 some under-the-hood cleanup of the project configurations

Changes in file stubs/Clang/orderfile:
 some under-the-hood cleanup of the project configurations

Changes in file stubs/Config/CommonConfig.xcconfig:
 some under-the-hood cleanup of the project configurations
 namely: FRAMEWORK_VERSION

Changes in file stubs/Config/Debug.xcconfig:
 some under-the-hood cleanup of the project configurations

Changes in file stubs/Config/Release.xcconfig:
 some under-the-hood cleanup of the project configurations
 namely: DEBUG_INFORMATION_FORMAT and PRODUCT_NAME

Changes in file stubs/Config/XcodeBuildGlueConfig.xcconfig:
 some under-the-hood cleanup of the project configurations

Changes in file stubs/Config/XcodeCompileToolsDebug.xcconfig:
 some under-the-hood cleanup of the project configurations
 including MACOSX_DEPLOYMENT_TARGET

Changes in file stubs/Config/XcodeCompileToolsRelease.xcconfig:
 some under-the-hood cleanup of the project configurations
 namely: DEPLOYMENT_POSTPROCESSING based on DEPLOYMENT_LOCATION now

Changes in file stubs/Config/XcodeTestingConfig.xcconfig:
 some under-the-hood cleanup of the project configurations

Changes in file tests/test_git_config.bash:
 As part of added prototype tool scripts

Changes in file unittests/test_build_paths_start:
 As part of added prototype tool scripts

Deletions from file XCMBuild.docc/XCRunShell.md:
 Removed template doc until tool becomes more than a shell wrapper.

diff --git a/bin/serialized b/bin/serialized
--- a/bin/serialized
+++ b/bin/serialized
@@ -86,7 +86,13 @@ function safetyCheckSerialized() {
 	else
 		if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
 			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized input. ( unsupported input )" 1>&2 ;
+			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
+				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: Negitive inputs makes no sense! ( garbage input )" 1>&2 ;
+			fi ;
 			false ;
+			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] ; then
+				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: warning: No more than a single input was expected. ( input overload )" 1>&2 ;
+			fi ;
 		fi ;
 		if [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -lt 0 ) ]] ; then
 			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized output. ( unsupported output )" 1>&2 ;
@@ -97,5 +103,37 @@ function safetyCheckSerialized() {
 }
 
 export -f safetyCheckSerialized ;
+
+
+# logic:
+# check if $# is even
+# branch on true and assume (in1,out1 ... in-n,out-n) style
+# on branch TODO ....
+# else if $# is odd check that $1 is a file (abort if missing)
+# branch if $1 is a file
+# on branch run $0 in-n out-n from n=1 until n>($#/2)
+
+function autoSerializeArgsAsToFrom() {
+	if [[ -z ${1} ]] || [[ -z ${2} ]] ; then
+		echo "${FUNCNAME[${BASH_SHLVL:-0}]:-$0}:${BASH_LINENO:-0}: note: expected serialized script mode. ( attempting ${FUNCNAME:-$_} )" 1>&2 ;
+		exec ${SHELL:-/bin/bash} -c "SCRIPT_INPUT_FILE_COUNT=1 ; SCRIPT_OUTPUT_FILE_COUNT=1 ; SCRIPT_INPUT_FILE_0=\${1} ; SCRIPT_OUTPUT_FILE_0=\${2} ; $0 ; exit $? ;" ;
+	else
+		if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
+			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized input. ( unsupported input )" 1>&2 ;
+			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
+				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: Negitive inputs makes no sense! ( garbage input )" 1>&2 ;
+			fi ;
+			false ;
+			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] ; then
+				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: warning: No more than a single input was expected. ( input overload )" 1>&2 ;
+			fi ;
+		fi ;
+		if [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -lt 0 ) ]] ; then
+			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized output. ( unsupported output )" 1>&2 ;
+			false ;
+		fi ;
+		true ;
+	fi ;
+}
 
 # source to include
