Changes in file bin/serialized:  - reworked safetyCheckSerialized  - also `export -f safetyCheckSerialized ;`

diff --git a/bin/serialized b/bin/serialized
--- a/bin/serialized
+++ b/bin/serialized
@@ -87,7 +87,7 @@ function safetyCheckSerialized() {
 		if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
 			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized input. ( unsupported input )" 1>&2 ;
 			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
-				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: Negitive inputs makes no sense! ( garbage input )" 1>&2 ;
+				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: Negative inputs makes no sense! ( garbage input )" 1>&2 ;
 			fi ;
 			false ;
 			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] ; then
@@ -116,32 +116,18 @@ export -f safetyCheckSerialized ;
 # usage autoVectorTypeSPMD CMD SRC1 DST1 ...
 
 function autoSerializeArgsAsToFrom() {
-	false;
-	return ;
 	if [[ ( $# -ne 2 ) ]] || [[ -z ${1} ]] || [[ -z ${2} ]] ; then
+		echo "Auto-serialize failed!" >&2 ;
+		false ;
+	else
 	# if -z $1 && -n $SCRIPT_INPUT_FILE_0 then RECURSION_a
 	# elif -z $2 && -n $SCRIPT_INPUT_FILE_0 && (basename $1) != (basename $SCRIPT_INPUT_FILE_0) then RECURSION_b
 	# elif -z $2 && -n $SCRIPT_INPUT_FILE_0 && -n $SCRIPT_INPUT_FILE_1 && (basename $1) == (basename $SCRIPT_INPUT_FILE_0) then RECURSION_b_a
 	# elif $# -ge 2 -n $SCRIPT_INPUT_FILE_0 && -z $SCRIPT_OUTPUT_FILE_0 && (basename $1) == (basename $SCRIPT_INPUT_FILE_0) then RECURSION_c (one in to many out )
 		echo "${FUNCNAME[${BASH_SHLVL:-0}]:-$0}:${BASH_LINENO:-0}: note: expected serialized script mode. ( attempting ${FUNCNAME:-$_} )" 1>&2 ;
 		fn_do_cmd "SCRIPT_INPUT_FILE_COUNT=1 ; SCRIPT_OUTPUT_FILE_COUNT=1 ; SCRIPT_INPUT_FILE_0=${1} ; SCRIPT_OUTPUT_FILE_0=${2} ; ${0} ; exit $? ;" ; wait ; exit $? ;
-	else
-		if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
-			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized input. ( unsupported input )" 1>&2 ;
-			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -lt 0 ) ]] ; then
-				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: Negitive inputs makes no sense! ( garbage input )" 1>&2 ;
-			fi ;
-			false ;
-			if [[ ( ${SCRIPT_INPUT_FILE_COUNT} -gt 1 ) ]] ; then
-				echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: warning: No more than a single input was expected. ( input overload )" 1>&2 ;
-			fi ;
-		fi ;
-		if [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -gt 1 ) ]] || [[ ( ${SCRIPT_OUTPUT_FILE_COUNT} -lt 0 ) ]] ; then
-			echo "${FUNCNAME:-$0}:${BASH_LINENO:-0}: error: failed to validate serialized output. ( unsupported output )" 1>&2 ;
-			false ;
-		fi ;
-		true ;
 	fi ;
+	false ;
 }
 
 # source to include
